#122: Added security group functionality to yandex bundle.
arenadata/ansible-module-yandex-cloud pull request #37
Opened 2022-08-19 06:26 UTC by Eddyredline

What was done:
1. Added update SGs feature.

2022-08-30 09:51 UTC, Maunty requested changes

2022-08-30 09:51 UTC, Maunty commented on modules/ycc_vm.py
> +            - update_sg
We should not move adcm problems into ansible module.

2022-09-14 17:25 UTC, gklepach approved these changes

2022-09-14 17:54 UTC, Maunty approved these changes
Commit body is empty! Bad practice!
I recommend to squash commits, first 2 commits are practically useless.

2022-09-15 06:29 UTC, merged